Complete the the page and adding some files
atatm/setup-and-mobile-project pull request #2
Opened 2022-09-24 15:24 UTC by atatm

I have almost done what I have to do now. I do those things to do like they were in Figma as much as possible since this is my first week I don't keep my time. so I suffer a shortage of time.

2022-09-24 16:07 UTC, mgmediaweb requested changes
Hi @atatm, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost1](https://user-images.githubusercontent.com/41912912/192106452-6ad7c78d-7779-4618-8781-faa24c086140.gif)

## Highlights 💯 
- Clear and descriptive Pull Request. ✔️ 
- Clean and tidy code. ✔️ 

## Required Changes ♻️

- Kindly, I suggest you use the readme template, provided by Microverse, this will make your presentation more readable. (remove titles you don't use, but keep the formatting).
- Kindly I suggest you to use H1 heading for your main text (index.html - line 33 to 34)
- Kindly, I suggest you remove the code that you are not using, this will make your website look more professional when seen by another programmer. (index.html - line 19 to 27)
- Kindly, I suggest you use UL/LI listing when lite icons. with separated icons and "A" tag. Also, whenever you use an image, indicate a descriptive ALT tag, that will greatly help the accessibility of your site. (index.html line 40)
- Kindly, I suggest where it says "my-logo" to put your name, as this is the main logo it should be an "a" tag and have a link to Home. (index.html - line 16)
- Kindly, I suggest you implement a header where it contains your logo and the navigation bar (at this moment it will only contain the hamburger menu), I indicate an example below. (index.html - line 13 to 29)
![carbon (6)](https://user-images.githubusercontent.com/41912912/192106888-879defb9-73d0-4647-892d-4e9a00239708.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Indicate the correct title of your site (index.html - line 9)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 16:07 UTC, mgmediaweb commented on index.html
> +         <img src="images/Frame2.png" alt="">
I kindly suggest using text in this section and ordering with a UL/LI listing.

2022-09-24 16:07 UTC, mgmediaweb commented on index.html
> +         <img  src="images/Tags.png" alt="">
Kindly, I suggest you use HTML text in this section and put the specifications in order with a UL/LI listing.

2022-09-24 16:07 UTC, mgmediaweb commented on index.html
> +        <img src="images/Action.png" alt="">
Kindly, I suggest you use HTML text in this section and put the specifications in order with a UL/LI listing.

2022-09-24 16:07 UTC, mgmediaweb commented on index.html
> +    <img src="images/SnapshootPortfolio2.png" alt=""></div>
Kindly, I suggest that for accessibility every time you use an "IMG" you indicate an appropriate "ALT" to describe the content of that image

2022-09-24 16:07 UTC, mgmediaweb commented on index.html
> +    <img src="images/primaryText.png" alt="">
Kindly, I suggest you use HTML text in this section and put the specifications in order with a UL/LI listing.

2022-09-24 16:07 UTC, mgmediaweb commented on index.html
> +    <img src="images/Tags2.png" alt="">
Kindly, I suggest you use HTML text in this section and put the languages in order with a UL/LI listing.

2022-09-24 16:07 UTC, mgmediaweb commented on index.html
> +      <img src="images/Action2.png" alt="">
Kindly, I suggest that for accessibility every time you use an "IMG" you indicate an appropriate "ALT" to describe the content of that image

2022-09-24 16:07 UTC, mgmediaweb commented on index.html
> +    <img src="images/SnapshootPortfolio3.png" alt="">
Kindly, I suggest that for accessibility every time you use an "IMG" you indicate an appropriate "ALT" to describe the content of that image

2022-09-24 16:07 UTC, mgmediaweb commented on index.html
> +     <img src="images/PrimaryText3.png" alt="">
Kindly, I suggest you use HTML text in this section and put the specifications in order with a UL/LI listing.

2022-09-24 16:07 UTC, mgmediaweb commented on index.html
> +      <img src="images/tags6.png" alt="">
Kindly, I suggest you use HTML text in this section and put the specifications in order with a UL/LI listing.

2022-09-24 16:07 UTC, mgmediaweb commented on index.html
> +      <img src="images/Action6.png" alt="">
Kindly, I suggest you use HTML text in this section and put the specifications in order with a UL/LI listing.

2022-09-24 16:07 UTC, mgmediaweb commented on index.html
> +    <img src="images/SnapshootPortfolio6.png" alt="">
Kindly, I suggest that for accessibility every time you use an "IMG" you indicate an appropriate "ALT" to describe the content of that image

2022-09-24 16:07 UTC, mgmediaweb commented on index.html
> +    <img src="images/LeftBlock6.png" alt="">
Kindly, I suggest you use HTML text in this section and put the specifications in order with a UL/LI listing.

2022-09-24 16:07 UTC, mgmediaweb commented on index.html
> +   <img src="images/TOP.png" alt="">
Kindly, I suggest you use HTML text in this section and put the specifications in order with a UL/LI listing.

2022-09-24 16:07 UTC, mgmediaweb commented on index.html
> +    <img src="images/SkillList.png" alt="">
Kindly, I suggest you use HTML text in this section and put the specifications in order with a UL/LI listing.

2022-09-24 16:07 UTC, mgmediaweb commented on index.html
> +  </div>
Kindly, I suggest you remove the pieces of code that you are not using, this will make your site cleaner and more elegant.

2022-09-24 16:07 UTC, mgmediaweb commented on index.css
> +  height: 5410px;
Kindly, I suggest you not to use fixed dimensions, it is better to use percentages so that your website adapts to the size of any mobile device.

2022-09-24 16:07 UTC, mgmediaweb commented on index.css
> +
Kindly, I suggest you not to use fixed dimensions, it is better to use percentages so that your website adapts to the size of any mobile device. (line 11 to 12)

2022-09-24 16:07 UTC, mgmediaweb commented on index.css
> +
Kindly, I suggest you use flexbox to center elements to your container and make your site adapt to the size of any mobile device. (line 85)

2022-09-24 17:07 UTC, mgmediaweb requested changes
Hi @atatm , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![work2](https://user-images.githubusercontent.com/41912912/192110256-78575e93-c360-4df7-8ef4-c4a86ec71306.gif)

 ## Highlights 💯 
- I appreciate your effort, you can do it! ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 17:07 UTC, mgmediaweb commented on index.html
> +   <h1>I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need coded, don’t hes
Kindly, for accessibility your web page should only contain a single H1 tag, for this case use a P tag

2022-09-24 17:07 UTC, mgmediaweb commented on index.html
> +         <img src="images/Frame2.png" alt="">
Kindly, I don't see this request reflected in your code

2022-09-24 17:07 UTC, mgmediaweb commented on index.html
> +         <img  src="images/Tags.png" alt="">
Kindly, I don't see this request reflected in your code

2022-09-24 17:07 UTC, mgmediaweb commented on index.html
> +        <img src="images/Action.png" alt="">
Kindly, I don't see this request reflected in your code

2022-09-24 17:07 UTC, mgmediaweb commented on index.html
> +    <img src="images/SnapshootPortfolio2.png" alt=""></div>
Kindly, I don't see this request reflected in your code

2022-09-24 17:07 UTC, mgmediaweb commented on index.html
> +    <img src="images/primaryText.png" alt="">
Kindly, I don't see this request reflected in your code

2022-09-24 17:07 UTC, mgmediaweb commented on index.html
> +    <img src="images/Tags2.png" alt="">
Kindly, I don't see this request reflected in your code

2022-09-24 17:07 UTC, mgmediaweb commented on index.html
> +      <img src="images/Action2.png" alt="">
Kindly, I don't see this request reflected in your code

2022-09-24 17:07 UTC, mgmediaweb commented on index.html
> +    <img src="images/SnapshootPortfolio3.png" alt="">
Kindly, I don't see this request reflected in your code

2022-09-24 17:07 UTC, mgmediaweb commented on index.html
> +     <img src="images/PrimaryText3.png" alt="">
Kindly, I don't see this request reflected in your code

2022-09-24 17:07 UTC, mgmediaweb commented on index.html
> +      <img src="images/tags6.png" alt="">
Kindly, I don't see this request reflected in your code

2022-09-24 17:07 UTC, mgmediaweb commented on index.html
> +      <img src="images/Action6.png" alt="">
Kindly, I don't see this request reflected in your code

2022-09-24 17:07 UTC, mgmediaweb commented on index.html
> +    <img src="images/SnapshootPortfolio6.png" alt="">
Kindly, I don't see this request reflected in your code

2022-09-24 17:07 UTC, mgmediaweb commented on index.html
> +    <img src="images/LeftBlock6.png" alt="">
Kindly, I don't see this request reflected in your code

2022-09-24 17:07 UTC, mgmediaweb commented on index.html
> +   <img src="images/TOP.png" alt="">
Kindly, I don't see this request reflected in your code

2022-09-24 17:07 UTC, mgmediaweb commented on index.html
> +    <img src="images/SkillList.png" alt="">
Kindly, I don't see this request reflected in your code

2022-09-24 17:07 UTC, mgmediaweb commented on index.html
> +  </div>
Kindly, I don't see this request reflected in your code

2022-09-24 22:52 UTC, christianbiring1 approved these changes
Hi @atatm , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [ ] All linters are passing
## Optional suggestions
- [ ] Make sure you implemented all the changes with the [OPTIONAL ] flag fir the will tahe your project to the next level.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-27 05:46 UTC, merged

2022-10-11 09:05 UTC, atatm commented
I think I cant submit it at this time.



On Sat, Sep 24, 2022 at 8:07 PM Gonzalo Medina ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @atatm <https://github.com/atatm> ,
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet.
>
> [image: work2]
> <https://user-images.githubusercontent.com/41912912/192110256-78575e93-c360-4df7-8ef4-c4a86ec71306.gif>
> Highlights 💯
>
>    - I appreciate your effort, you can do it! ✔️
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/atatm/setup-and-mobile-project/pull/2#discussion_r979275797>
> :
>
> >      I’m Mariane Glad to see you!!
>
> -   </h2>
>
> -   <p>I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need coded, don’t hestiate to contact me.</p>
>
> +   </h1>
>
> +   <h1>I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need coded, don’t hestiate to contact me.</h1>
>
>
> Kindly, for accessibility your web page should only contain a single H1
> tag, for this case use a P tag
> ------------------------------
>
> In index.html
> <https://github.com/atatm/setup-and-mobile-project/pull/2#discussion_r979275939>
> :
>
> > @@ -41,5 +41,83 @@ <h3>LETS CONNECT</h3></div>
>
>     </div>
>
>    </div>
>
>  </section>
>
> +<section class="second">
>
> +  <div class="cardwork1">
>
> +    <div class="portfolio">
>
> +      <img src="images/SnapshootPortfolio.png" alt="">
>
> +    </div>
>
> +    <div class="leftblock">
>
> +      <div class="priimaryText">
>
> +         <h2>Tonic</h2>
>
> +         <img src="images/Frame2.png" alt="">
>
>
> Kindly, I don't see this request reflected in your code
> ------------------------------
>
> In index.html
> <https://github.com/atatm/setup-and-mobile-project/pull/2#discussion_r979275947>
> :
>
> > @@ -41,5 +41,83 @@ <h3>LETS CONNECT</h3></div>
>
>     </div>
>
>    </div>
>
>  </section>
>
> +<section class="second">
>
> +  <div class="cardwork1">
>
> +    <div class="portfolio">
>
> +      <img src="images/SnapshootPortfolio.png" alt="">
>
> +    </div>
>
> +    <div class="leftblock">
>
> +      <div class="priimaryText">
>
> +         <h2>Tonic</h2>
>
> +         <img src="images/Frame2.png" alt="">
>
> +        </div>
>
> +         <p>A daily selection of privately personalized reads; no accounts or sign-ups required.</p>
>
> +        <div class ="tags">
>
> +         <img  src="images/Tags.png" alt="">
>
>
> Kindly, I don't see this request reflected in your code
> ------------------------------
>
> In index.html
> <https://github.com/atatm/setup-and-mobile-project/pull/2#discussion_r979275949>
> :
>
> > +<section class="second">
>
> +  <div class="cardwork1">
>
> +    <div class="portfolio">
>
> +      <img src="images/SnapshootPortfolio.png" alt="">
>
> +    </div>
>
> +    <div class="leftblock">
>
> +      <div class="priimaryText">
>
> +         <h2>Tonic</h2>
>
> +         <img src="images/Frame2.png" alt="">
>
> +        </div>
>
> +         <p>A daily selection of privately personalized reads; no accounts or sign-ups required.</p>
>
> +        <div class ="tags">
>
> +         <img  src="images/Tags.png" alt="">
>
> +        </div>
>
> +         <div class="action">
>
> +        <img src="images/Action.png" alt="">
>
>
> Kindly, I don't see this request reflected in your code
> ------------------------------
>
> In index.html
> <https://github.com/atatm/setup-and-mobile-project/pull/2#discussion_r979275964>
> :
>
> > +         <h2>Tonic</h2>
>
> +         <img src="images/Frame2.png" alt="">
>
> +        </div>
>
> +         <p>A daily selection of privately personalized reads; no accounts or sign-ups required.</p>
>
> +        <div class ="tags">
>
> +         <img  src="images/Tags.png" alt="">
>
> +        </div>
>
> +         <div class="action">
>
> +        <img src="images/Action.png" alt="">
>
> +
>
> +  </div>
>
> +  </div>
>
> +</div>
>
> +<div class="cardwork2">
>
> +  <div class="portfolio2">
>
> +    <img src="images/SnapshootPortfolio2.png" alt=""></div>
>
>
> Kindly, I don't see this request reflected in your code
> ------------------------------
>
> In index.html
> <https://github.com/atatm/setup-and-mobile-project/pull/2#discussion_r979275967>
> :
>
> > +         <p>A daily selection of privately personalized reads; no accounts or sign-ups required.</p>
>
> +        <div class ="tags">
>
> +         <img  src="images/Tags.png" alt="">
>
> +        </div>
>
> +         <div class="action">
>
> +        <img src="images/Action.png" alt="">
>
> +
>
> +  </div>
>
> +  </div>
>
> +</div>
>
> +<div class="cardwork2">
>
> +  <div class="portfolio2">
>
> +    <img src="images/SnapshootPortfolio2.png" alt=""></div>
>
> +  <div class="leftblock2">
>
> +  <div class="texts">
>
> +    <img src="images/primaryText.png" alt="">
>
>
> Kindly, I don't see this request reflected in your code
> ------------------------------
>
> In index.html
> <https://github.com/atatm/setup-and-mobile-project/pull/2#discussion_r979275990>
> :
>
> > +
>
> +  </div>
>
> +  </div>
>
> +</div>
>
> +<div class="cardwork2">
>
> +  <div class="portfolio2">
>
> +    <img src="images/SnapshootPortfolio2.png" alt=""></div>
>
> +  <div class="leftblock2">
>
> +  <div class="texts">
>
> +    <img src="images/primaryText.png" alt="">
>
> +  </div>
>
> +   <div class="primaryText">
>
> +   <p>A daily selection of privately personalized reads; no accounts or sign-ups required.</p>
>
> +   </div>
>
> +   <div class="Tags2">
>
> +    <img src="images/Tags2.png" alt="">
>
>
> Kindly, I don't see this request reflected in your code
> ------------------------------
>
> In index.html
> <https://github.com/atatm/setup-and-mobile-project/pull/2#discussion_r979275992>
> :
>
> > +</div>
>
> +<div class="cardwork2">
>
> +  <div class="portfolio2">
>
> +    <img src="images/SnapshootPortfolio2.png" alt=""></div>
>
> +  <div class="leftblock2">
>
> +  <div class="texts">
>
> +    <img src="images/primaryText.png" alt="">
>
> +  </div>
>
> +   <div class="primaryText">
>
> +   <p>A daily selection of privately personalized reads; no accounts or sign-ups required.</p>
>
> +   </div>
>
> +   <div class="Tags2">
>
> +    <img src="images/Tags2.png" alt="">
>
> +   </div>
>
> +    <div class="Action2">
>
> +      <img src="images/Action2.png" alt="">
>
>
> Kindly, I don't see this request reflected in your code
> ------------------------------
>
> In index.html
> <https://github.com/atatm/setup-and-mobile-project/pull/2#disc [...]