Contact Form Validation
atatm/setup-and-mobile-project pull request #4
Opened 2022-10-04 20:26 UTC by atatm

I Add a contact form as recommended and I also did form validations that are recommended to do.

2022-10-04 22:08 UTC, codecaiine requested changes
Hi @AbdimulhinYussuf3675 @Wolfmikerson @atatm , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Descriptive PR :heavy_check_mark: 
- No linters errors :heavy_check_mark: 
- Good commits history :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-04 22:08 UTC, codecaiine commented on index.html
> +    <form action="#" method="post">
- [ ] Please make sure  form `action` integrate the [formspree service](https://formspree.io/html) in order to collect data as expected :smile: 
Please check the example below :arrow_down: 
```
<form action="https://formspree.io/f/{form_id}" method="post">
  <label for="email">Your Email</label>
  <input name="Email" id="email" type="email">
  <button type="submit">Submit</button>
</form>

```

2022-10-04 22:08 UTC, codecaiine commented on index.html
> +          <textarea id="subject" name="subject" class="form1" placeholder="Write your message here"
- [ ] I would like to recommend you to not use an inline style because **Inline styles don't separate content from design:** They are exactly the same as embedded font and other clunky design tags that modern developers rail against. Please fix it :+1:

2022-10-04 22:08 UTC, codecaiine commented on index.html
> +      </div>
- [ ] Please make sure that your button has a `submit` type.  It is used to submit all the user values to the form handler. Please fix it :smile:

2022-10-04 22:08 UTC, codecaiine commented on index.css
> +}
- [ ] Good job so far with your contact form :clap: But I noticed that your contact design is a little bit different from the Figma template :cry: Please make sure that You must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) and make sure that you use Flexbox In order to lay out the elements on the page 
 as a developer it is important to pay attention to details and design that will give a good experience to your user :smile: 

#### Your design
![Screenshot from 2022-10-04 21-25-46](https://user-images.githubusercontent.com/6615394/193937825-47c4fe81-2554-4653-ac41-d101b733b1fb.png)

#### Figma
![Screenshot from 2022-10-04 21-40-24](https://user-images.githubusercontent.com/6615394/193938359-a42fe03b-1972-4951-adcb-37788ebd2de2.png)
![Screenshot from 2022-10-04 21-39-54](https://user-images.githubusercontent.com/6615394/193938362-555b6fb9-9773-47ef-85a4-cb3f8dda879f.png)


- [ ] Please make sure that your button is similar to the one on the Figma template :smile: and implement the button interactions (enable, hover, etc.).
![Screenshot from 2022-10-04 21-40-34](https://user-images.githubusercontent.com/6615394/193938268-32ef221d-d154-410d-94b4-6c7970dd1ff6.png)

![Screenshot from 2022-10-04 22-03-44](https://user-images.githubusercontent.com/6615394/193938712-c8f31f92-8820-418d-970f-2dad9279911d.png)

2022-10-05 09:16 UTC, roshan-bajgain requested changes
Hi @atatm, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-05 09:16 UTC, roshan-bajgain commented on index.html
> +      <br>
- [ ] I would suggest you please stick as much as possible to the design font, color, and spacing. Please fix the spaing of the right and left side as there is no spacing in the design. See the image below for the design
### Your design
![your](https://user-images.githubusercontent.com/81727988/194024547-11bae01a-c506-4dc5-9bc8-eba516a36aca.png)
### Figma design

![fimga](https://user-images.githubusercontent.com/81727988/194024638-cb652a4d-42ca-4514-8791-c9a7aeec3f07.png)

2022-10-05 09:16 UTC, roshan-bajgain commented on index.html
> +      </div>
- [ ] Please remove the black border to stick to the Figma design

2022-10-05 09:16 UTC, roshan-bajgain commented on index.html
> +      <div class="form">
- [ ] As requested by the previous reviewer you should create an account on Formspree and use it. Here is the link for the lesson [Link](https://formspree.io/html/)

2022-10-06 09:23 UTC, cwaku approved these changes
Hi @atatm 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
 - [x] Good job overall following the template design 💯 
 - [x] Correct GitHub Flow 👍🏾 
 - [x] Good commit history 🥇 
 - [x] Good PR title/description 💯 
 - [x] All linters passed 🥇 
 
![](https://media.giphy.com/media/mGK1g88HZRa2FlKGbz/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. The previous reviewer simply missed some of them, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-06 09:23 UTC, cwaku commented on style.css
> +
[OPTIONAL]
- [ ] Good job attempting to fix the changes regarding the spacing around the contact form but there is one more to meet the required changes of the reviewer. I suggest that you remove the `margin-right: 50px` to get rid of the space.

Your Design | Figma Design
--|--
![image](https://user-images.githubusercontent.com/29071984/194275272-70fbefbe-276c-4f1e-a9ba-b8aed8447ebe.png) | <img src="https://user-images.githubusercontent.com/81727988/194024638-cb652a4d-42ca-4514-8791-c9a7aeec3f07.png" />

2022-10-06 09:30 UTC, atatm commented
Thank you for your feedback.

On Thu, Oct 6, 2022 at 12:23 PM Ricky Mormor ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @atatm <https://github.com/atatm>
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
> Highlights
>
>    - Good job overall following the template design 💯
>    - Correct GitHub Flow 👍🏾
>    - Good commit history 🥇
>    - Good PR title/description 💯
>    - All linters passed 🥇
>
>
> <https://camo.githubusercontent.com/9ab1354ab399a31c604186cd2e7c09a0d4704215a1eda3e29a02fc52bf3f6bf5/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6d474b31673838485a526132466c4b47627a2f67697068792e676966>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you consider them as they can improve
> your code. The previous reviewer simply missed some of them, and addressing
> them will improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Remember to tag me in your question so I can receive the notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561>, you have
> a limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In style.css
> <https://github.com/atatm/setup-and-mobile-project/pull/4#discussion_r988778304>
> :
>
> > +
>
> +.contact-me {
>
> +  background: url(./images/Contactme1.png);
>
> +  margin-top: 70px;
>
> +  font-family: 'Poppins', Arial, Helvetica, sans-serif;
>
> +  width: 375px;
>
> +  height: 750px;
>
> +  text-align: center;
>
> +  color: white;
>
> +  margin-right: 50px;
>
> +}
>
> +
>
>
> [OPTIONAL]
>
>    - Good job attempting to fix the changes regarding the spacing around
>    the contact form but there is one more to meet the required changes of the
>    reviewer. I suggest that you remove the margin-right: 50px to get rid
>    of the space.
>
> Your Design Figma Design
> [image: image]
> <https://user-images.githubusercontent.com/29071984/194275272-70fbefbe-276c-4f1e-a9ba-b8aed8447ebe.png>
> <https://user-images.githubusercontent.com/81727988/194024638-cb652a4d-42ca-4514-8791-c9a7aeec3f07.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/atatm/setup-and-mobile-project/pull/4#pullrequestreview-1132621528>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZKNXDH3C7XNN2Q7RWLGOV3WB2LBZANCNFSM6AAAAAAQ45NQ44>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-06 09:32 UTC, merged